name: annotation
description: Flutter Project by ITCoderz. Flutter SDK Version for the app is 3.10.6 .

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  dropdown_button2: ^2.3.6
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  animated_splash_screen: ^1.3.0
  web_socket_channel: ^2.4.0
  shared_preferences: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter_icons:
  image_path: "assets/images/app_icon/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/fonts/bembo/
    - assets/images/app_icon/
    - assets/images/light_mode/
    - assets/images/dark_mode/
    - assets/images/dark_mode/splash_screen_background_image/
    - assets/images/dark_mode/splash_logo/
    - assets/images/dark_mode/landing_screen_images/
    - assets/images/dark_mode/success_annotation_image/
    - assets/images/dark_mode/selection_screen_dark_images/
    - assets/images/dark_mode/incubator_images/
    - assets/images/dark_mode/whats_happening_images/
    - assets/images/dark_mode/baby_next_condition/
    - assets/images/dark_mode/baby_next_condition/baby_behaviour/
    - assets/images/dark_mode/baby_next_condition/movement_in/
    - assets/images/dark_mode/baby_next_condition/baby_voice/
    - assets/images/dark_mode/baby_next_condition/breathing/
    - assets/images/dark_mode/baby_next_condition/eyes/
    - assets/images/light_mode/whats_happening_screen/
    - assets/images/light_mode/splash_screen/
    - assets/images/light_mode/incubator_state/
    - assets/images/light_mode/selection_screen/
    - assets/images/light_mode/
    - assets/images/camera_id_images/

  fonts:
    - family: Bembo Std
      fonts:
        - asset: assets/fonts/bembo/BemboStd.ttf
        - asset: assets/fonts/bembo/BemboStd-Bold.ttf
        - asset: assets/fonts/bembo/BemboStd-Italic.ttf

